### ISSUE TITLE
Unable to create injector

### ISSUE THREAD

**Issue by JimiIT92** [SpongePowered/sponge-plugin-template#1]
I was trying to test this template to then customize to my needs, but as soon as I run the server, no matter if with the provided code or customized one, I get this error:

```
[Guice/MissingConstructor]: No injectable constructor for type Example.
class Example does not have a @Inject annotated constructor or a no-arg constructor.
Caused by: com.google.inject.CreationException: Unable to create injector
```

I have this even with a clean forked project.

**STEPS TO REPRODUCE**
- Fork/Clone this repository
- Open the project in IntelliJ Idea
- Run Gradle task `runServer`

**Comment by zml2008** [comment]
I can't seem to reproduce this locally, are you able to provide more info, like branch, api rev, current OS, etc?

**Comment by JimiIT92** [comment]
Sorry for late response, I was in a very very long disease situation :( Anyway, after updating IntelliJ it suddendly worked, so maybe there was something failing on their end :/
